import requests


OLLAMA_URL = "http://localhost:11434/api/generate"

MODEL = "llama3.2:3b"


question = """
What is Fetch and Pay in BBPS?
"""


context = """
Source: Procedural_Guidelines_BBPS_V6_November_2025_Website_b15d06fcb5.pdf
Page: 17

BBPS has in all 4 Biller transaction flows which are listed below-

i. Fetch and Pay: Customer does financial transaction
post fetching the bill (e.g., Electricity bill).

ii. Validation and Pay: Customer does financial
transaction post validation of their identifier.
"""


answer = """
Fetch and Pay is a BBPS service where customers
automatically pay their recurring electricity bills
every month without needing to fetch the bill.
"""


prompt = f"""
You are evaluating an answer generated by an AI
system using retrieved documents.

QUESTION:
{question}

RETRIEVED CONTEXT:
{context}

AI ANSWER:
{answer}

Evaluate the answer on three dimensions.

1. CORRECTNESS

Does the answer correctly answer the question
based on the retrieved context?

2. FAITHFULNESS

Are the claims in the answer supported by the
retrieved context?

3. RELEVANCE

Does the answer directly address the question?

Return ONLY valid JSON in this exact structure:

{{
    "correctness": "PASS or FAIL",
    "faithfulness": "PASS or FAIL",
    "relevance": "PASS or FAIL",
    "explanation": "short explanation"
}}
"""


response = requests.post(
    OLLAMA_URL,
    json={
        "model": MODEL,
        "prompt": prompt,
        "stream": False
    },
    timeout=120
)

response.raise_for_status()

result = response.json()["response"]

print("\n====================================")
print("EVALUATION RESULT")
print("====================================")

print(result)